project:
  type: website
  output-dir: docs

website:
  title: "Matthew Weirick Johnson"
  favicon: logo.png
  google-analytics: "G-XN49YP77PL"
  open-graph: true
  twitter-card: 
    creator: "@xoxoMattyBoy"
    image: "/portraits/portrait-2.jpg"
  navbar:
    left:
      - href: research/index.qmd
        text: Research
      - href: talks/index.qmd
        text: Presentations
      - href: CV/index.qmd
        text: CV
      - text: Projects
        menu: 
          - projects.qmd
          - projects/project1.qmd
          - projects/project2.qmd
      - href: blog.qmd
        text: Blog
    right:
    - text: Connect with me
      menu: 
        - text: "{{< fa envelope size=xl >}} Email" 
          href: mailto:matt@mattweirick.com
        - text: "{{< fa brands twitter size=xl >}} Twitter"
          href: https://twitter.com/xoxoMattyBoy
        - text: "{{< fa brands linkedin size=xl >}} LinkedIn"
          href: https://www.linkedin.com/in/matthew-w-johnson
        - text: "{{< fa brands instagram size=xl >}} Instagram"
          href: https://instagram.com/mattbrarian
        - text: "{{< fa brands github size=xl >}} GitHub"
          href: https://github.com/mattweirick
        - text: "{{< ai google-scholar size=xl >}} Google Scholar"
          href: https://scholar.google.com/citations?user=dgbjIWIAAAAJ&hl=en
        - text: "{{< ai orcid size=xl >}} ORCiD"
          href: https://orcid.org/0000-0002-6391-2088
        - text: "{{< ai researcherid size=xl >}} Researcher ID"
          href: https://www.webofscience.com/wos/author/record/AFE-4307-2022
        - text: "{{< ai scopus size=xl >}} Scopus Author ID"
          href: http://www.scopus.com/inward/authorDetails.url?authorI
  sidebar: 
    style: "docked"
    search: true
    title: "Matthew Weirick Johnson"
    

format:
  html:
    theme: theme.scss #was cosmo ??flatly ??litera (nice but needs some accessibility adjustment) ??lux (meh?) ??pulse (purple) ??sandstone (basic)
    #like pillbox for bnuttons
    css: styles.css
    toc: true

editor: visual
