---
title: "Training Library Instructors"
author: "Matthew Weirick Johnson"
description: "Pedagogy impacts all parts of library work and culture. It changes the way we interact with learners regardless of setting and however we name or define the teaching moment from research help to outreach to leading meetings. Pedagogy is a praxis of relation, and studying it can improve all aspects of our work and organizations.</br></br>In two volumes, <i>Training Library Instructors</i> collects examples of how we train our colleagues to teach, whether they’re student workers, non-librarian staff, new or experienced librarians, or something else entirely. <i>Volume 1, A Guide to Training Graduate Students</i>, focuses on teacher training for graduate students in LIS programs and in academic libraries. It presents existing literature and theories, approaches to teaching library school students to teach, and critical reflections from librarians about their varied experiences receiving teacher training. In <i>Volume 2, A Guide to Training Librarians,</i> librarians share their knowledge about teaching, learning, and pedagogy through a variety of replicable activities: formal and informal workshops, courses, communities of practice, peer observation, and more.</br></br>Training Library Instructors provides detailed, easily implemented and modified plans for courses, internships, teach-the-teacher programs, and other instructional methods and opportunities for graduate students and library workers at all levels of teaching experience."
title-block-banner: "#a8aca6"
title-block-banner-color: black
page-layout: article
date: 2024-09
date-format: MMMM YYYY
draft: true
aliases: 
  - /training-library-instructors/
  - /TLI
---

## Vol 1: A Guide to Training Graduate Students

### Table of Contents

### Acknowledgments

### Introduction

### Teaching & Learning in the LIS Curriculum: Theory, Practice, and Need

1.  Practice Theory in Information Literacy; Logan Rath
2.  Library Instruction Training and the MLIS: A Review of the Literature; Matthew Weirick Johnson

### Case Studies

3.  Using Teaching Demonstrations in Graduate-Level Instruction Courses; Melissa A. Wong
4.  Teaching Instruction Librarians by Design; Dominique Turnbow & Amanda Roth
5.  From Intern to Instructor: Training to Teach With Primary Sources - Rachel Makarowski & Maureen Maryanski
6.  Reflections on the Information Literacy Scholars Program at Syracuse University Libraries; Kelly Delevan, Breeann Austin, Brie Baumert, Rebecca McCall, Lauren Quackenbush, Olivia Russo, Alayna L. Vander Veer, and B. Austin Waters
7.  Introducing Emerging Library Instructors to Information Literacy Instruction through Programmatic Instruction; Alicia G. Vaandering, Amanda Izenstark, Colin Braun, Erin Cunningham, Reina Kirkendall, and Laura Marasco

### Reflections: LIS Instruction Training

8.  Creating My Own Experience: Navigating a Library Graduate Program Without Library Instruction Training; Kala Dunn
9.  The Impact of a Graduate Assistantship and Optional Courses on Becoming a Teaching Librarian; Chrissy O'Grady
10. From Learner to Teacher: Preparing for the Library Instruction Classroom and Fostering Teacher Identity Through Information Literacy Coursework; Kaci Wilson
11. From Library Science Student to Instruction Librarian: Using the Science and Art of Teaching to Grow as an Instruction Librarian; Mark W. Duncan

### Reflections: Non-LIS Instruction Training

12. Benefits of An Elementary School Teaching Background for Academic Library Instruction; Amber Owrey
13. Thoughts from a Teacher Librarian: Utilizing Training as a Teacher to Become an Instructional Librarian; Ella Gibson
14. Changing Roles: Lessons Learned from Applying Non-LIS Teacher Training to Library Instruction; Jeremiah Mercurio
15. Having a Teaching Background Doesn't Solve All of Your Library Instruction Questions, But Learning From Each Other Might; Alexandra Mitchell

### Conclusion: Advancing Teaching & Learning in the LIS Curriculum

### Author Biographies

## Vol 2: A Guide to Training Librarians

### Table of Contents

### Acknowledgements

### Introduction

### Case Studies: Continuing Training for Library Instructors

16. Developing Library Instructors Together: A Case Study from the Hong Kong JULAC Consortium; Victoria Caplan, Christopher Chan, Lisa Janicke Hinchliffe, Eunice S. P. Wong
17. Increasing Inclusive Instruction: Building a Bespoke In-house Teacher Training Programme at the University of Cambridge; Kirstie Preest & Claire Sewell
18. Communities of Support: Using the Community of Practice Model for Library Instructor Development; Melissa A. Wong & Laura Saunders

### Case Studies: Training New Librarians

19. We're All in this Together: Holistic Approaches to Training New Instruction Librarians; Randi Beem, Marc Bess, Ryan Harris, Abby Moore, Natalie Ornat Bitting, Catherine Tingelstad, Angel Truesdale
20. Learning What Works: Training New Library Instructors During a Pandemic and Beyond; Josette M. Kubicki, Tonya D. Dority, Thomas C. Weeks, and Emma Kate Morgan

### Case Studies: Training New and Experienced Librarians

21. Planning for Instruction Training: Implementing an On-the-job Training for Library Instructors; Livia Piotto
22. Supporting Librarian Teachers: The Learning-Centred Librarian Instruction Program at the University of Victoria; Karen Munro, Cynthia Korpan, Matt Huculak, and Michael Lines
23. Best of Both Worlds: Training for New and Experienced Instructors; David X. Lemmons, Ashley Blinstrub, Kayla M. Gourlay, Maoria J. Kirker, Janna Mattson, and Anna K. Murphy-Lang

### Reflections

24. The Introverted Instructor: Tackling Library Instruction When It's Out of Your Comfort Zone; Ginelle Baskin
25. (Eventually) Learning to Look Before I Leap: Discovering Instructional Design Mid-Career; Nicole Westerdahl
26. Observing the Observed: Autotheory as a Practice of Instruction; Russel Peterson
27. It Takes a Village to Raise a Librarian; Sam Mandani & Fannie Ouyang
28. Go and Get What You Need!: Seeking Out Mentorship; Jamia Williams

### Conclusion: Moving Instruction Training Forward in Academic Libraries

### Author Biographies
