---
title: "Matthew Weirick Johnson"
page-layout: article
bibliography: "My Publications.bib"
nocite: |
  @*
csl: apa-cv.csl
css: cv.css
format:
  html:
    toc: true
    suppress-bibliography: true
  #pdf:
    #pdf-engine: lualatex
    #documentclass: scrartcl
    #cite-method: biblatex
    #biblatexoptions: maxbibnames=99, sorting=ydnt, style=apa-cv, dashed=false, terseinits=true, date=year
    #mainfont: Helvetica
    #monofont: Helvetica
    #sansfont: Helvetica
    #keep-tex: true
    #urlcolor: Black
    #include-in-header: 
    #  - text: |
    #      \usepackage{enumitem}
format-links: [pdf]
listing:
  - id: published-papers-2026
    include: 
      type: "Published"
      year: 2026
    contents: ../research/papers.yaml
    template: papers2.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    type: table
    field-display-names: 
      year: "Year"
      journal: "Journal"
  - id: published-papers-2025
    include: 
      type: "Published"
      year: 2025
    contents: ../research/papers.yaml
    template: papers2.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    type: table
    field-display-names: 
      year: "Year"
      journal: "Journal"
  - id: published-papers-2024
    include: 
      type: "Published"
      year: 2024
    contents: ../research/papers.yaml
    template: papers2.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    type: table
    field-display-names: 
      year: "Year"
      journal: "Journal"
  - id: published-papers-2023
    include: 
      type: "Published"
      year: 2023
    contents: ../research/papers.yaml
    template: papers2.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    field-display-names: 
      year: "Year"
      journal: "Journal"
  - id: published-papers-2021
    include: 
      type: "Published"
      year: 2021
    contents: ../research/papers.yaml
    template: papers2.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    field-display-names: 
      year: "Year"
      journal: "Journal"
  - id: book-chapters
    include: 
      type: "Published"
    contents: ../research/chapters.yaml
    template: chapters.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    field-display-names: 
      year: "Year"
      journal: "Journal"  
  - id: other
    include: 
      type: "Published"
    contents: ../research/other.yaml
    template: chapters.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    field-display-names: 
      year: "Year"
      journal: "Journal" 
  - id: talks-local
    include: 
      type: "Published"
      audience: 
        - "regional"
        - "local"
        - "institutional"
    contents: ../talks/talks.yaml
    template: talks2.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    field-display-names: 
      year: "Year"
      journal: "Journal"
  - id: talks-international
    include: 
      type: "Published"
      audience: 
        - "international"
        - "national"
    contents: ../talks/talks.yaml
    template: talks2.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    field-display-names: 
      year: "Year"
      journal: "Journal"
  - id: talks-invited
    include: 
      type: "Published"
      audience: 
        - "invited"
    contents: ../talks/talks.yaml
    template: talks2.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    field-display-names: 
      year: "Year"
      journal: "Journal"
  - id: talks-webinars
    include: 
      type: "Published"
      audience: 
        - "webinar"
    contents: ../talks/talks.yaml
    template: talks2.ejs
    filter-ui: false
    sort: "date desc" 
    sort-ui: false
    categories: false
    field-display-names: 
      year: "Year"
      journal: "Journal"
---

```{=html}
<style>

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
  }

#quarto-document-content li + li {
    margin-top: .5em;
   }
   
#education li + li {
    margin-top:.1em;
}

#education li + li:last-child {
    margin-bottom: .5em;
}
   
#education li {
    margin: 0 0 0 2em;
      }

#education h3 {
  font-size: var(--bs-body-font-size);
  font-weight: 600;
}

#academic-positions li li {
    margin: 0 0 0 2em;
      }

#academic-positions h3 {
  font-size: var(--bs-body-font-size);
  font-weight: 600;
}

</style>
```

::: {.content-visible when-format="html"}
Matthew Weirick Johnson, MSLS is the Director of Research & Instruction at the University of South Florida Libraries and a PhD student in Educational Measurement and Evaluation also at USF. You can also [view a PDF of my CV](/files/johnson-cv.pdf).
:::

## <i class="fa-solid fa-graduation-cap"></i> Education

### PhD Candidate in Measurement & Research

```{=html}
<ul>
  <li>
    University of South Florida
    <span class="cvdate">exp. 2027</span>
  </li>
  
  <li class="cv-details-item">
    <div class="cv-details">
      <div class="cv-detail-label">Certificates:</div>
      <div class="cv-detail-value">
        <div>Qualitative Research</div>
        <div>Advanced Quantitative Research</div>
        <div>Women's, Gender &amp; Sexuality Studies</div>
      </div>
    </div>
  </li>
  
</ul>
```

### MA in Women's, Gender, and Sexuality Studies

```{=html}
<ul>
  <li>
    University of South Florida
    <span class="cvdate">exp. 2027</span>
  </li>
</ul>
```

### MS in Library Science (specialization in Academic Libraries)

```{=html}
<ul>
  <li>
    University of North Carolina at Chapel Hill
    <span class="cvdate">2018</span>
  </li>

  <li class="cv-details-item">
    <div class="cv-details">
      <div class="cv-detail-label">Master's Paper:</div>
      <div class="cv-detail-value">
        “Not playing that game”: An exploratory study of queer men's health
        information behavior on location-aware dating and sex-seeking mobile
        applications
      </div>

      <div class="cv-detail-label">Certificates:</div>
      <div class="cv-detail-value">

  <div>Interdisciplinary Health Communication</div>
  <div>Interdisciplinary Health Disparities</div>
  <div>SILS Diversity Advocate</div>

      </div>
    </div>
  </li>
</ul>
```

### BA in English (concentration in Literature)

```{=html}
<ul>
  <li>
    Virginia Tech
    <span class="cvdate">2016</span>
  </li>
</ul>
```

<!---

### University of South Florida

```{=html}
<ul>
  <li>
    <strong>PhD</strong> <em>Measurement &amp; Research</em>
    <span class="cvdate">exp. 2027</span>
  </li>

  <li>
    <strong>MA</strong> <em>Women's, Gender &amp; Sexuality Studies</em>
    <span class="cvdate">exp. 2027</span>
  </li>

  <li class="cv-details-item">
    <div class="cv-details">
      <div class="cv-detail-label">Certificates:</div>
      <div class="cv-detail-value">
        <div>Qualitative Research</div>
        <div>Advanced Quantitative Research</div>
        <div>Women's, Gender &amp; Sexuality Studies</div>
      </div>
    </div>
  </li>
</ul>
```


### University of North Carolina at Chapel Hill

```{=html}
<ul>
  <li>
    <strong>MS</strong> <em>Library Science</em>
    <span class="cvdate">2018</span>
  </li>

  <li class="cv-details-item">
    <div class="cv-details">
      <div class="cv-detail-label">Master's Paper:</div>
      <div class="cv-detail-value">
        “Not playing that game”: An exploratory study of queer men's health
        information behavior on location-aware dating and sex-seeking mobile
        applications
      </div>

      <div class="cv-detail-label">Certificates:</div>
      <div class="cv-detail-value">

  <div>Interdisciplinary Health Communication</div>
  <div>Interdisciplinary Health Disparities</div>
  <div>SILS Diversity Advocate</div>

      </div>
    </div>
  </li>
</ul>
```

--->

```{=html}
<!--- Awards: Pratt Severn Best Student Research Paper Award, ASIS&T --->
```

<!--
### Virginia Tech

- **BA** *English* [2016]{.cvdate}
--->

```{=html}
<!--- Awards: Barbara Ellen Smith Outstanding Paper Award, VT Women's & Gender Studies; Ut Prosim Award for Service, VT English --->
```

## <i class="fa-solid fa-school"></i> Academic Positions


### University of South Florida

- **Associate Librarian & Director** [**2023 -- Present**]{.cvdate}
  - Director of Research & Instruction
  
### University of California, Los Angeles

- **Associate Librarian** [**2019 -- 2023**]{.cvdate}
  - Humanities & Social Sciences Librarian [2019 -- 2023]{.cvdate}
  - Lead for Teaching & Learning [2020 -- 2023]{.cvdate}
  - Humanities & Social Sciences Lead for Research Services [2020 -- 2022]{.cvdate}

## <i class="fa-solid fa-bookmark"></i> Publications

::: {.content-visible when-format="html"}
A complete list of publications with available open access options can be found on my [Research](/research) page.
:::

### <i class="fa-solid fa-book"></i> Edited Books

- *Training Library Instructors, Vol 1: A Guide to Training Graduate Students* <br/> <small class="text-muted" style="display:block;"> Matthew Weirick Johnson (Ed.). ACRL. </small>
- *Training Library Instructors, Vol 2: A Guide to Training Librarians* <br/> <small class="text-muted" style="display:block;"> Matthew Weirick Johnson (Ed.). ACRL. </small>

### <i class="fa-solid fa-file-lines"></i> Peer-reviewed Articles

#### 2026

::: {#published-papers-2026 style="padding-bottom: 0;"}
:::

#### 2025

::: {#published-papers-2025 style="padding-bottom: 0;"}
:::

#### 2024

::: {#published-papers-2024 style="padding-bottom: 0;"}
:::

::: {.content-visible when-format="pdf"}
:::

#### 2023

::: {#published-papers-2023 style="padding-bottom: 0;"}
:::

#### 2021

::: {#published-papers-2021 style="padding-bottom: 0;"}
:::

### <i class="fa-solid fa-book-open"></i> Book Chapters

::: {#book-chapters style="padding-bottom: 0;"}
:::

### <i class="fa-solid fa-pen-nib"></i> Other Publications

::: {#other}
:::

## <i class="fa-solid fa-bullhorn"></i> Talks & Presentations

### International & National

::: {#talks-international}
:::

### Regional, Local & Institutional

::: {#talks-local}
:::

### Invited Talks

::: {#talks-invited}
:::

### Webinars

::: {#talks-webinars}
:::

## <i class="fa-solid fa-magnifying-glass"></i> Editorial & Peer Review Service

### Editorial Service

- *College & Research Libraries*, Social Media Editor [2023 -- 2026]{.cvdate}
- ACRL *Choice*, Editorial Board Member [2023 -- 2025]{.cvdate}
- *Public Services Quarterly*, Editorial Board Member [2023 -- Present]{.cvdate}

### Peer Reviews

- *The Journal of Academic Librarianship* [18 reviews (2023 -- 2026)]{.cvdate}
- *Public Services Quarterly* [9 reviews (2023 -- 2026)]{.cvdate}
- *College & Research Libraries* [4 reviews (2023 -- 2026)]{.cvdate}
- *Journal of New Librarianship* [3 reviews (2021 -- 2023)]{.cvdate}
- *New Media & Society* [3 reviews (2021)]{.cvdate}
- *Journal of Information Literacy* [1 review (2024)]{.cvdate}
- *Journal of the Medical Library Association* [1 review (2022)]{.cvdate}
- *Library Journal* [1 review (2024)]{.cvdate}
- *Qualitative Inquiry* [1 review (2025)]{.cvdate}

## <i class="fa-solid fa-people-group"></i> Professional Service

### American Library Association (ALA)

- Conference Committee, ACRL Representative [2022 -- 2023]{.cvdate}

#### Association of College & Research Libraries (ACRL)

- Conference Contributed Papers Committee, Member [2024 -- 2025]{.cvdate}
- Publications Coordinating Committee, Member [2023 -- 2025]{.cvdate}
- Choice Editorial Board, Member [2023 -- 2025]{.cvdate}
- *College & Research Libraries* Editorial Board, Member [2023 -- 2026]{.cvdate}
- Nominations and Policies Audit Task Force, Chair [2022 -- 2023]{.cvdate}
- Professional Development Committee, Chair [2022 -- 2023]{.cvdate}
- Professional Development Committee, Member [2019 -- 2022]{.cvdate}

##### ACRL Instruction Section (IS)

- Management and Leadership Committee, Member [2026 -- 2028]{.cvdate}
- Nominating Committee, Chair [2025 -- 2026]{.cvdate}
- Executive Committee, Archivist [2024 -- 2025]{.cvdate}
- Executive Committee, Secretary [2023 -- 2024]{.cvdate}
- Peer-reviewed Instructional Materials Online (PRIMO) Committee, Member [2023 -- 2025]{.cvdate}
- Diversity and Inclusion Task Force, Member [2018 -- 2020]{.cvdate}

##### ACRL University Libraries Section (ULS)

- Professional Development Committee, Co-Chair [2025 -- 2027]{.cvdate}
- Professional Development Committee, Member [2023 -- 2025]{.cvdate}

##### ACRL Women and Gender Studies Section (WGSS)

- Core Books Project (HIV & AIDS, British Literature), Member [2021 -- Present]{.cvdate}
- Awards Committee, Member [2021 -- 2023]{.cvdate}

##### Rainbow Round Table (RRT)

- Stonewall Book Awards - Israel Fishman Non-Fiction Award Committee, Member [2022 -- 2024]{.cvdate}
- News & Reviews Committee, Member [2019 -- 2021]{.cvdate}
- Resources Committee, Member [2017 -- 2019]{.cvdate}

#### Library Instruction Round Table (LIRT)

- Top 20 Committee, Member [2023 -- 2027]{.cvdate}
- Newsletter Committee, Member [2017 -- 2019]{.cvdate}

### American Educational Research Association (AERA)

#### Qualitative Research Special Interest Group (QRSIG)

- Graduate Student Travel Award Committee, Member [2026 -- 2027]{.cvdate}

### Institute for Research Design in Librarianship (IRDL)

- Mentor [2023 -- 2024]{.cvdate}
